#!/bin/bash

# [[ STEP 0 - CHECKS ]] #
# [[ STEP 0.1 - MESSAGES ]] #
ini="is not installed!"
sudofail="This script needs to be run as root or with sudo."
sudoget="Got sudo rights."
# [[ END ]] #

# [[ STEP 0.2 - DEPCHECK ]] #
if ! command -v x86_64-w64-mingw32-gcc &> /dev/null
then
    echo "x86_64-w64-mingw32-gcc $ini"
    exit 1
fi

if ! command -v mkgpt &> /dev/null
then
    echo "mkgpt $ini"
    exit 1
fi

if ! command -v git &> /dev/null
then
    echo "git $ini"
    exit 1
fi

if ! command -v qemu-system-x86_64 &> /dev/null
then
    echo "qemu-system-x86_64 $ini"
    exit 1
fi

if ! command -v xorriso &> /dev/null
then
    echo "xorriso $ini"
    exit 1
fi

# [[ END ]] #

# [[ STEP 0.3 - SUDO CHECK ]] #
if [ "$EUID" -ne 0 ]; then
  echo "$sudofail"
  sudo echo "$sudoget"
  echo ""
fi
# [[ END ]] #

# [[ STEP 0 - END ]] #

# [[ STEP 1 - VARIABLES ]] #

# [[ STEP 1.1 - TOOLCHAIN ]] #
CC=x86_64-w64-mingw32-gcc
LD=x86_64-w64-mingw32-gcc
QM=qemu-system-x86_64
XR=xorriso
# [[ END ]] #

# [[ STEP 1.2 - DIRECTORIES ]] #
EFIDIR="/media/mypassisdexuu/'dexuu_s Data'/OSDevToolchain/gnu-efi"
# [[ END ]] #

# [[ STEP 1.3 - FLAGS ]] #
CCFLAGS="-ffreestanding -I$EFIDIR -I$EFIDIR/protocol -I$EFIDIR/x86_64 -IUEFI/gnu-efi -ILibraries -c"
LDFLAGS="-nostdlib -Wl,-dll -shared -Wl,--subsystem,10 -e efi_main"
QMFLAGS="-L OVMF_dir/ -pflash OVMF.fd -hda hdimage.bin"
GPTFLAGS="-o hdimage.bin --image-size 4096 --part fat.img --type system"
XRFLAGS=""
# [[ END ]] #

# [[ STEP 1.4 - BOOLEANS ]] #
skip_compile=false
skip_ld=false
skip_img=false
skip_qm=false
skip_iso=false
skip_git=false
# [[ END ]]#

# [[ STEP 1 - END]] #

# [[ STEP 2 - MAKING THE IMAGE ]] #
for arg in "$@"; do
    case "${arg,,}" in
        -nc) skip_compile=true ;;
        -nl)    skip_ld=true ;;
        -nm)    skip_img=true ;;
        -nq)    skip_qm=true ;;
        -ni)    skip_iso=true ;;
        -ng)    skip_git=true
    esac
done

if [ "$skip_git" = false ]; then
    echo "Saving to Git..."

fi

if [ "$skip_compile" = false ]; then
    echo "Compiling..."
fi

if [ "$skip_ld" = false ]; then
    echo "Linking..."
fi

if [ "$skip_img" = false ]; then
    echo "Making FAT.IMG..."

fi

if [ "$skip_iso" = false ]; then
    echo "Making an ISO..."
fi

if [ "$skip_qm" = false ]; then
    echo "Starting QEMU..."
    $QM $QMFLAGS
fi